/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.45
 * Generated at: 2021-06-17 12:07:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class b_005fcss_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <!-- 부트스트랩 css파일참조 -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/bootstrap.css\">\n");
      out.write("    <!-- 부트스트랩 js를 사용하기 위해서 jquery라이브러리 참조 -->\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\n");
      out.write("\n");
      out.write("    <!-- 부트스트랩 js참조 -->\n");
      out.write("    <script src=\"js/bootstrap.js\"></script>\n");
      out.write("    <!--개인 디자인-->\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/basic.css\">\n");
      out.write("    <!--로그인디자인-->\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/login.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/info.css\"> \n");
      out.write("    <link rel=\"stylesheet\" href=\"css/thanks.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/forgot.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/board.css\">\n");
      out.write("\n");
      out.write("    <!--보드디자인-->\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/board.css\">\n");
      out.write("    \n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Mate+SC&display=swap\" rel=\"stylesheet\">\n");
      out.write("<style>\n");
      out.write("    *{\n");
      out.write("        font-family: 'Mate SC', serif;\n");
      out.write("    }\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("<title>Insert title here</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write(" <header>\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"inner-logo\">\n");
      out.write("                <a href=\"index.jsp\">the vanp</a>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"inner-list\">\n");
      out.write("                <a href=\"login.jsp\">login</a>\n");
      out.write("                <a href=\"join.jsp\">join</a>\n");
      out.write("                <a href=\"board.jsp\">board</a>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("        </div>\n");
      out.write("    </header>\n");
      out.write("\n");
      out.write("    <section>\n");
      out.write("        <div class=\"col-lg-12 b-group\">\n");
      out.write("            <span class=\"board-list-home\" ><a href=\"board.html\">Home</a></span>\n");
      out.write("            <span class=\"board-list\" ><a href=\"boardcss.html\">HTML & CSS</a></span>\n");
      out.write("            <span class=\"board-list\" ><a href=\"boardjava.html\">JAVA</a></span>\n");
      out.write("            <span class=\"board-list\" ><a href=\"boardjsp.html\">JSP</a></span>\n");
      out.write("            <span class=\"board-list\" ><a href=\"boardjs.html\">JS</a></span>\n");
      out.write("            <span class=\"board-list\" ><a href=\"boarddb.html\">DB</a></span>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"container\">\n");
      out.write("          <div class=\"col-lg-12 code-group\">\n");
      out.write("              <div class=\"code-title\"><a href=\"\">HTML & CSS</a></div>\n");
      out.write("              <hr>\n");
      out.write("\n");
      out.write("              <div class=\"code-box\">\n");
      out.write("                <div class=\"code-title\">\n");
      out.write("                    <p class=\"p-num\">num</p>\n");
      out.write("                    <p class=\"p-title\">title</p>\n");
      out.write("                    <p class=\"p-id\">id</p>\n");
      out.write("                    <p class=\"p-date\">date</p>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("              </div>\n");
      out.write("              <input type=\"button\" value=\"write\" class=\"btn board-btn\" onclick=\"location.href='writer'\">\n");
      out.write("              </div>\n");
      out.write("             \n");
      out.write("\n");
      out.write("              </div>\n");
      out.write("\n");
      out.write("              </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("    </section>\n");
      out.write(" \n");
      out.write("    <footer>\n");
      out.write("        <div class=\"foot\">\n");
      out.write("            <ul>\n");
      out.write("                <li><a href=\"https://www.instagram.com/1997kg_f/?hl=ko\">Instagram</a></li>\n");
      out.write("                <li><a href=\"https://blog.naver.com/thevanppp\">Blog</a></li>\n");
      out.write("                <li><a href=\"\">Email</a></li>\n");
      out.write("                <li><a href=\"index.html\">@thevanppp</a></li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("     </footer>\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
