/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.45
 * Generated at: 2021-06-09 12:30:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/include/footer.jsp", Long.valueOf(1622811192000L));
    _jspx_dependants.put("/include/header.jsp", Long.valueOf(1623241676000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("    \n");
      out.write(" ");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write(" <title>Document</title>\n");
      out.write("       <link rel=\"stylesheet\" href=\"css/bootstrap.css\">\n");
      out.write("    <!-- 부트스트랩 js를 사용하기 위해서 jquery라이브러리 참조 -->\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\n");
      out.write("\n");
      out.write("    <!-- 부트스트랩 js참조 -->\n");
      out.write("    <script src=\"js/bootstrap.js\"></script>\n");
      out.write("    <!--개인 디자인-->\n");
      out.write("   \n");
      out.write("    <link rel=\"stylesheet\" href=\"css/basic.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/info.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/thanks.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/login.css\">\n");
      out.write("     <link rel=\"stylesheet\" href=\"css/forgot.css\">\n");
      out.write("\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\"> \n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Mate+SC&display=swap\" rel=\"stylesheet\">\n");
      out.write("<style>\n");
      out.write("    *{\n");
      out.write("        font-family: 'Mate SC', serif;\n");
      out.write("    }\n");
      out.write("    </Style>\n");
      out.write("  \n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write(" <header>\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"inner-logo\">\n");
      out.write("                <a href=\"index.jsp\">the vanp</a>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"inner-list\">\n");
      out.write("                <a href=\"login.jsp\">login</a>\n");
      out.write("                <a href=\"join.jsp\">join</a>\n");
      out.write("                <a href=\"board.jsp\">board</a>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("        </div>\n");
      out.write("    </header>\n");
      out.write("    \n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\n");
      out.write(" \n");
      out.write(" <section>\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <aside class=\"col-md-6\">\n");
      out.write("                    <form action=\"login_ok.jsp\" method=\"post\" class=\"box\" >\n");
      out.write("                        <div class=\"form-login\">\n");
      out.write("                            <label for=\"\">ID</label>\n");
      out.write("                            <input type=\"text\" class=\"form-control\" name=\"id\" autocomplete=\"off\">\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"form-login\">\n");
      out.write("                            <label for=\"\">PASSWORD</label>\n");
      out.write("                            <input type=\"password\" class=\"form-control\" name=\"pw\" autocomplete=\"off\">\n");
      out.write("                        </div>\n");
      out.write("                        \n");
      out.write("                         <input type =\"submit\" value=\"Login\" class=\"btn btn-primary btn-block\" >\n");
      out.write("                         <input type =\"button\" value=\"Forgot password\" class=\"btn btn-primary btn-block\" onclick=\"location.href='forgot.jsp'\">\n");
      out.write("                       \n");
      out.write("                    </form>\n");
      out.write("                </aside>\n");
      out.write("\n");
      out.write("                <aside class=\"col-md-6\">\n");
      out.write("                    <div class=\"sub\">\n");
      out.write("                        혹시 아직 회원이 아니신가요 ?<br>\n");
      out.write("                        가입하시면 더 많은 혜택을 누리실 수 있습니다 !\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <input type =\"button\" value=\"Join\" class=\"btn btn-primary btn-block\" onclick=\"location.href='join.jsp'\">\n");
      out.write("                </aside>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("    \n");
      out.write(" \n");
      out.write(" ");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Document</title>\n");
      out.write("    \n");
      out.write("   \n");
      out.write("    <link rel=\"stylesheet\" href=\"css/bootstrap.css\">\n");
      out.write("   \n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\n");
      out.write("\n");
      out.write("    <script src=\"js/bootstrap.js\"></script>\n");
      out.write(" \n");
      out.write("    <link rel=\"stylesheet\" href=\"css/basic.css\">\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/login.css\">\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Mate+SC&display=swap\" rel=\"stylesheet\">\n");
      out.write("<style>\n");
      out.write("    *{\n");
      out.write("        font-family: 'Mate SC', serif;\n");
      out.write("    }\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("    <footer style =\"padding-top: 30px;\">\n");
      out.write("       <div class=\"foot\">\n");
      out.write("           <ul>\n");
      out.write("               <li><a href=\"https://www.instagram.com/1997kg_f/?hl=ko\">Instagram</a></li>\n");
      out.write("               <li><a href=\"https://blog.naver.com/thevanppp\">Blog</a></li>\n");
      out.write("               <li><a href=\"\">Email</a></li>\n");
      out.write("               <li><a href=\"index.html\">@thevanppp</a></li>\n");
      out.write("           </ul>\n");
      out.write("       </div>\n");
      out.write("    </footer>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
